# Docs for the Azure Web Apps Deploy action: https://github.com/azure/functions-action
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy to Azure Function App - keyspeech-eastus-1

on:
  push:
    branches:
      - main
  workflow_dispatch:

env:
  AZURE_FUNCTIONAPP_PACKAGE_PATH: '.'
  AZURE_FUNCTIONAPP_PROJECT_PATH: 'Keyspeech.PayPal/Keyspeech.PayPal.csproj'
  DOTNET_VERSION: '8.0.x'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions:
      id-token: write #This is required for requesting the JWT
      contents: read #This is required for actions/checkout

    steps:
      - name: 'Checkout GitHub Action'
        uses: actions/checkout@v4

      - name: Setup DotNet ${{ env.DOTNET_VERSION }} Environment
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}

      - name: 'Resolve Project Dependencies Using Dotnet'
        shell: bash
        run: |
          dotnet build '${{ env.AZURE_FUNCTIONAPP_PROJECT_PATH }}' --configuration Release --output ./output

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_6C2D7C55C2F34F2AB27B8BF30049A7F7 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_ABC538119BCC4175BB1E9FA71B99787F }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_DC3E42181E9048F989D5A8D602B0DB44 }}

      - name: 'Run Azure Functions Action'
        uses: Azure/functions-action@v1
        id: fa
        with:
          app-name: 'keyspeech-eastus-1'
          slot-name: 'Production'
          package: './output'